window_width = 1270.0
window_height = 720.0
fullscreen = false
vsync = true
graphic_backend = "auto"

chunk_range = 4
# ["low" = 64px / "medium" = 128px / "high" = 256px / "max" = 512px]
texture_res = "high"