# This file contains all things for game video settings. You can
# chnage the most of this ingame. Note: variables with #OnlyFile
# can change here only!

##############################################
#                  Window                    #
##############################################

window_resolution = "1270x720"
fullscreen = false
vsync = true
video_backend = "AUTO"

##############################################
#                Game Visuel                 #
##############################################

chunk_range = 8
texture_quality = "medium"